//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotionServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemotionServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address for connection:.
        /// </summary>
        public static string AdressString {
            get {
                return ResourceManager.GetString("AdressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IP adresses.
        /// </summary>
        public static string AvailableIpLabel {
            get {
                return ResourceManager.GetString("AvailableIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser - backward.
        /// </summary>
        public static string BrowserBackwardMenu {
            get {
                return ResourceManager.GetString("BrowserBackwardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser - forward.
        /// </summary>
        public static string BrowserForwardMenu {
            get {
                return ResourceManager.GetString("BrowserForwardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser refresh page.
        /// </summary>
        public static string BrowserRefreshPageMenu {
            get {
                return ResourceManager.GetString("BrowserRefreshPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close active window.
        /// </summary>
        public static string CloseActiveWindowMenu {
            get {
                return ResourceManager.GetString("CloseActiveWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to stop the server.
        /// </summary>
        public static string CloseConnectionClickHelper {
            get {
                return ResourceManager.GetString("CloseConnectionClickHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close connection.
        /// </summary>
        public static string CloseSocketButton {
            get {
                return ResourceManager.GetString("CloseSocketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string ConnectionTabHeader {
            get {
                return ResourceManager.GetString("ConnectionTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL+C.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:.
        /// </summary>
        public static string CurrentConnectionSettingsLabel {
            get {
                return ResourceManager.GetString("CurrentConnectionSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid port.
        /// </summary>
        public static string EnterValidPortTextBox {
            get {
                return ResourceManager.GetString("EnterValidPortTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your port.
        /// </summary>
        public static string EnterYourPortTextbox {
            get {
                return ResourceManager.GetString("EnterYourPortTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all windows.
        /// </summary>
        public static string ExpandAllMenu {
            get {
                return ResourceManager.GetString("ExpandAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut key №1.
        /// </summary>
        public static string FastButton1GroupBox {
            get {
                return ResourceManager.GetString("FastButton1GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut key №2.
        /// </summary>
        public static string FastButton2GroupBox {
            get {
                return ResourceManager.GetString("FastButton2GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose IP address, and then click &quot;Open connection&quot; button to start the server to listen to incoming messages from Remotion Client, installed on your android device..
        /// </summary>
        public static string HelpMainWindowButton {
            get {
                return ResourceManager.GetString("HelpMainWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet exception occured.
        /// </summary>
        public static string InternetExceptionString {
            get {
                return ResourceManager.GetString("InternetExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediate mode.
        /// </summary>
        public static string MediateModeButton {
            get {
                return ResourceManager.GetString("MediateModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize all windows.
        /// </summary>
        public static string MinimizeAllMenu {
            get {
                return ResourceManager.GetString("MinimizeAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string MinimizeButton {
            get {
                return ResourceManager.GetString("MinimizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string NothingMenu {
            get {
                return ResourceManager.GetString("NothingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here! Click on icon to expand..
        /// </summary>
        public static string NotifyIconBaloonText {
            get {
                return ResourceManager.GetString("NotifyIconBaloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click this button to start the server to listen to incoming messages from Remotion Client, installed on your android device.
        /// </summary>
        public static string OpenConnectionClickHelper {
            get {
                return ResourceManager.GetString("OpenConnectionClickHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open connection.
        /// </summary>
        public static string OpenSocketButton {
            get {
                return ResourceManager.GetString("OpenSocketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL+V.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to port: .
        /// </summary>
        public static string PortString {
            get {
                return ResourceManager.GetString("PortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restart program.
        /// </summary>
        public static string RestartApplicationString {
            get {
                return ResourceManager.GetString("RestartApplicationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll down.
        /// </summary>
        public static string ScrollDownMenu {
            get {
                return ResourceManager.GetString("ScrollDownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll sensitivity.
        /// </summary>
        public static string ScrollSpeedLabel {
            get {
                return ResourceManager.GetString("ScrollSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll up.
        /// </summary>
        public static string ScrollUpMenu {
            get {
                return ResourceManager.GetString("ScrollUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server exception occured.
        /// </summary>
        public static string ServerExceptionString {
            get {
                return ResourceManager.GetString("ServerExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTabHeader {
            get {
                return ResourceManager.GetString("SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection closed.
        /// </summary>
        public static string SocketClosedString {
            get {
                return ResourceManager.GetString("SocketClosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection opened.
        /// </summary>
        public static string SocketOpenedString {
            get {
                return ResourceManager.GetString("SocketOpenedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchpad sensitivity.
        /// </summary>
        public static string TouchpadSpeedLabel {
            get {
                return ResourceManager.GetString("TouchpadSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off sound.
        /// </summary>
        public static string TurnOffSoundMenu {
            get {
                return ResourceManager.GetString("TurnOffSoundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available IP addresses.
        /// </summary>
        public static string UpdateNetworkInfoHelper {
            get {
                return ResourceManager.GetString("UpdateNetworkInfoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume.
        /// </summary>
        public static string VolumeDownMenu {
            get {
                return ResourceManager.GetString("VolumeDownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase volume.
        /// </summary>
        public static string VolumeUpMenu {
            get {
                return ResourceManager.GetString("VolumeUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom in.
        /// </summary>
        public static string ZoomInMenu {
            get {
                return ResourceManager.GetString("ZoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom out.
        /// </summary>
        public static string ZoomOutMenu {
            get {
                return ResourceManager.GetString("ZoomOutMenu", resourceCulture);
            }
        }
    }
}
