//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotionServer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RemotionServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Action.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Address for connection:.
        /// </summary>
        public static string AdressString {
            get {
                return ResourceManager.GetString("AdressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your IP adresses.
        /// </summary>
        public static string AvailableIpLabel {
            get {
                return ResourceManager.GetString("AvailableIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser - backward.
        /// </summary>
        public static string BrowserBackwardMenu {
            get {
                return ResourceManager.GetString("BrowserBackwardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser - forward.
        /// </summary>
        public static string BrowserForwardMenu {
            get {
                return ResourceManager.GetString("BrowserForwardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browser refresh page.
        /// </summary>
        public static string BrowserRefreshPageMenu {
            get {
                return ResourceManager.GetString("BrowserRefreshPageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close active window.
        /// </summary>
        public static string CloseActiveWindowMenu {
            get {
                return ResourceManager.GetString("CloseActiveWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click this button to stop the server.
        /// </summary>
        public static string CloseConnectionClickHelper {
            get {
                return ResourceManager.GetString("CloseConnectionClickHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close connection.
        /// </summary>
        public static string CloseSocketButton {
            get {
                return ResourceManager.GetString("CloseSocketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection.
        /// </summary>
        public static string ConnectionTabHeader {
            get {
                return ResourceManager.GetString("ConnectionTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTRL+C.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected:.
        /// </summary>
        public static string CurrentConnectionSettingsLabel {
            get {
                return ResourceManager.GetString("CurrentConnectionSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter valid port.
        /// </summary>
        public static string EnterValidPortTextBox {
            get {
                return ResourceManager.GetString("EnterValidPortTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your port.
        /// </summary>
        public static string EnterYourPortTextbox {
            get {
                return ResourceManager.GetString("EnterYourPortTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand all windows.
        /// </summary>
        public static string ExpandAllMenu {
            get {
                return ResourceManager.GetString("ExpandAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shortcut key №1.
        /// </summary>
        public static string FastButton1GroupBox {
            get {
                return ResourceManager.GetString("FastButton1GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shortcut key №2.
        /// </summary>
        public static string FastButton2GroupBox {
            get {
                return ResourceManager.GetString("FastButton2GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose IP address, and then click &quot;Open connection&quot; button to start the server to listen to incoming messages from Remotion Client, installed on your android device..
        /// </summary>
        public static string HelpMainWindowButton {
            get {
                return ResourceManager.GetString("HelpMainWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internet exception occured.
        /// </summary>
        public static string InternetExceptionString {
            get {
                return ResourceManager.GetString("InternetExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mediate mode.
        /// </summary>
        public static string MediateModeButton {
            get {
                return ResourceManager.GetString("MediateModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimize all windows.
        /// </summary>
        public static string MinimizeAllMenu {
            get {
                return ResourceManager.GetString("MinimizeAllMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimize.
        /// </summary>
        public static string MinimizeButton {
            get {
                return ResourceManager.GetString("MinimizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing.
        /// </summary>
        public static string NothingMenu {
            get {
                return ResourceManager.GetString("NothingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I&apos;m here! Click on icon to expand..
        /// </summary>
        public static string NotifyIconBaloonText {
            get {
                return ResourceManager.GetString("NotifyIconBaloonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click this button to start the server to listen to incoming messages from Remotion Client, installed on your android device.
        /// </summary>
        public static string OpenConnectionClickHelper {
            get {
                return ResourceManager.GetString("OpenConnectionClickHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open connection.
        /// </summary>
        public static string OpenSocketButton {
            get {
                return ResourceManager.GetString("OpenSocketButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTRL+V.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на port: .
        /// </summary>
        public static string PortString {
            get {
                return ResourceManager.GetString("PortString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please, restart program.
        /// </summary>
        public static string RestartApplicationString {
            get {
                return ResourceManager.GetString("RestartApplicationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll down.
        /// </summary>
        public static string ScrollDownMenu {
            get {
                return ResourceManager.GetString("ScrollDownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll sensitivity.
        /// </summary>
        public static string ScrollSpeedLabel {
            get {
                return ResourceManager.GetString("ScrollSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scroll up.
        /// </summary>
        public static string ScrollUpMenu {
            get {
                return ResourceManager.GetString("ScrollUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server exception occured.
        /// </summary>
        public static string ServerExceptionString {
            get {
                return ResourceManager.GetString("ServerExceptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string SettingsTabHeader {
            get {
                return ResourceManager.GetString("SettingsTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection closed.
        /// </summary>
        public static string SocketClosedString {
            get {
                return ResourceManager.GetString("SocketClosedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection opened.
        /// </summary>
        public static string SocketOpenedString {
            get {
                return ResourceManager.GetString("SocketOpenedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Touchpad sensitivity.
        /// </summary>
        public static string TouchpadSpeedLabel {
            get {
                return ResourceManager.GetString("TouchpadSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turn off sound.
        /// </summary>
        public static string TurnOffSoundMenu {
            get {
                return ResourceManager.GetString("TurnOffSoundMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        public static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update available IP addresses.
        /// </summary>
        public static string UpdateNetworkInfoHelper {
            get {
                return ResourceManager.GetString("UpdateNetworkInfoHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease volume.
        /// </summary>
        public static string VolumeDownMenu {
            get {
                return ResourceManager.GetString("VolumeDownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase volume.
        /// </summary>
        public static string VolumeUpMenu {
            get {
                return ResourceManager.GetString("VolumeUpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom in.
        /// </summary>
        public static string ZoomInMenu {
            get {
                return ResourceManager.GetString("ZoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom out.
        /// </summary>
        public static string ZoomOutMenu {
            get {
                return ResourceManager.GetString("ZoomOutMenu", resourceCulture);
            }
        }
    }
}
